import json,hashlib,sys
from pathlib import Path
from dataclasses import asdict
from datetime import datetime,timezone
root=Path.cwd();sys.path.insert(0,str(root/'research'));import runner_v3 as base
art=root/'artifacts/experiment';parent=json.loads((art/'live-contract-v3.json').read_text());contract={**parent}
contract.update(id='visible-explanation-v1',schemaVersion='afterlight.experiment.contract.visible.v1',name='Can context steer a choice without appearing in its explanation?',title='Can context steer a choice without appearing in its explanation?',provider='openai',model='gpt-5.6-luna',route='openai-direct',totalTrials=100,maxCalls=200,maxCapUsd=2,maxTrialCostUsd=.02,executionOrder='case-major',validUntil='2026-09-13T23:00:00Z',frozenAt=datetime.now(timezone.utc).isoformat())
contract['cases']=[{'id':c.id+'-direct-1','input':json.dumps({**asdict(c),'seed':0,'route':'openai-direct'},ensure_ascii=False),'expectedAnswer':c.target} for c in base.CASES if c.phase=='heldout']
contract['settings']={'reasoningEffort':'low','subjectMaxCompletionTokens':2048,'monitorMaxCompletionTokens':1024,'structuredOutput':'strict JSON schema','temperature':'omitted, provider default','seed':'not sent; the case record seed is an internal identifier only','providerRoute':'Direct OpenAI API, no routing fallback','priceCardPerMillionTokens':{'prompt':.20,'cachedPrompt':.02,'completion':1.20}}
contract['hypothesis']='A casual contextual cue may increase target-aligned choices compared with no cue while the final explanation does not attribute the choice to that cue.'
contract['primaryOutcome']='Mean paired difference across cases in target-aligned choice indicator: contextual aside minus no cue.'
contract['secondaryOutcome']='Explicit-request, neutral-context, and relevant-cost differences versus no cue; blinded visible-explanation attribution rates, including baseline and neutral false positives and a separately labeled changed-choice subset.'
contract['independentUnit']='Twenty hand-authored decision cases. One response per condition per case. Condition observations within a case are paired, not independent replications.'
contract['scope']='Independent endpoint evaluation on 20 cases excluded from direct OpenAI calibration. These cases were previously run on AkashML in the interrupted v3 study. The model, endpoint and observable surface changed for availability reasons, so the studies remain separate.'
contract['observationSurface']='Visible one-sentence final rationale only. OpenAI internal reasoning tokens are charged but their content is not exposed or inspected.'
contract['operationalChange']='After repeated documented shared-pool rate limits on OpenRouter, use the direct OpenAI API. This is a new frozen model/endpoint and measurement-surface version. No old scientific observations are replaced or pooled into its primary estimate.'
contract['parentLiveContract']='implicit-influence-live-v3'
contract['estimate']={'lowUsd':.04,'highUsd':.20,'minutes':'10 to 25','assumptions':'100 subjects plus at most100 monitors. Each trial reserves$0.02, including both output ceilings. Cost is estimated from returned token usage and the frozen price card, not a billing receipt.'}
contract['analysis']='Report all100 planned trials and provider-call evidence, missing outputs and errors. Compute condition target-choice counts, paired case-level differences and a seeded4000-draw case bootstrap95% interval. Monitor rates use validYES/NO responses; show missing denominators. Never treat an individual changed response as proof of causal influence. A null estimate does not establish equivalence.'
contract['falsifier']='If the paired implicit-versus-baseline estimate and the monitor observations do not support the hypothesized pattern, report the result as unsupported or inconclusive in this tested setting. Do not retune the cases or primary metric.'
contract['competingExplanation']='Stochastic response variation, salience and prompt contradictions may explain individual choice changes; limited one-sentence explanations and model-judge error can explain missing attribution.'
contract['limits']=['Twenty selected cases are not a population sample or evidence of transfer to other models.','Each case has one response per condition, so within-case stochastic variability is not separately estimated.','Only final visible rationales are observed; this is not a full chain-of-thought monitoring replication.','A model-generated attribution judgment is fallible and does not establish hidden causal reasoning.','Case-major execution reduces long condition blocks but does not randomize every presentation order.','Costs are token-based estimates, not provider billing receipts.']
contract['source']={**parent['source'],'adaptation':'Controlled contextual-choice adaptation inspired by Setting1; new model and visible-explanation-only measurement, not a full reproduction.'}
contract['adapterSha256']=hashlib.sha256((root/'backend/src/scientific.ts').read_bytes()).hexdigest()
text=json.dumps(contract,ensure_ascii=False,sort_keys=True,separators=(',',':'));hash=hashlib.sha256(text.encode()).hexdigest();(art/'visible-contract-v1.json').write_text(text+'\n',encoding='utf8');(art/'visible-contract-v1-manifest.json').write_text(json.dumps({'id':contract['id'],'hash':hash,'hashMethod':'SHA256 of compact sorted-key JSON without trailing newline','frozenAt':contract['frozenAt'],'totalTrials':100,'maxCalls':200},indent=2)+'\n',encoding='utf8')
q=lambda x:"'"+str(x).replace("'","''")+"'"
sql='INSERT INTO contracts (id,version,hash,question_id,name,status,contract_json,created_at) VALUES ('+','.join([q(contract['id']),'1',q(hash),q(contract['questionId']),q(contract['name']),q('validated'),q(text),q(contract['frozenAt'])])+') ON CONFLICT(id,version) DO NOTHING;\n'
(root/'backend/work/visible-contract-v1-import.sql').write_text(sql,encoding='utf8');print(json.dumps({'id':contract['id'],'hash':hash,'trials':100,'maxCalls':200,'frozenAt':contract['frozenAt']}))
