import { addPersonaProposal } from './persona-proposal.mjs';
import fs from 'node:fs/promises';
const notes={
'2608.04735': ['Implicit influence','Compares implicit and explicit contextual influence across four task families and seven extended-thinking models. The authors report lower detection of some implicit influences, with further degradation under some guidance prompts. This is the closest source for our bounded behavioral adaptation.','Seven extended-thinking models; paper results are distinct from our API pilot.'],
'2608.29464': ['Implicit influence','FACE-Eval varies preference-cue channel and explicitness. Across 15 open-weight models, the authors report less verbalized attribution for tool-return and implicit cues. Their source-attribution intervention has mixed effects, so changing cue placement or attribution prompts is established prior work.','15 open-weight models; single-call, prefilled-tool setting.'],
'2607.22925': ['Accessible reasoning','Tests whether semantically uninformative filler tokens can support reasoning and hidden task constraints. The findings challenge the assumption that all consequential computation appears as interpretable output text. They do not establish that every unexplained decision uses the same mechanism.','13 frontier models; synthetic tasks and a hidden modular-arithmetic constraint.'],
'2609.04194': ['Measurement','Compares judges of reasoning-step importance against estimates from repeated continuations. Capable judges recover some information, but legible text remains an incomplete guide to a step\'s functional contribution. This motivates separating an explanation judgment from a causal measurement.','Monte Carlo continuation estimates; judging performance remains below the estimated noise ceiling.'],
'2607.09786': ['Reward compatibility','Trains reasoning models with length penalties and measures hint influence and monitorability. The authors compare compressed traces with length-matched deletion controls, finding that compression can remove more monitorable evidence than shortening alone predicts. An API output cap is a different intervention.','Qwen3 4B and 14B; training intervention and five evaluation distributions.'],
'2608.04928': ['Accessible reasoning','Compares monitoring with explicit and latent reasoning, using hints as controlled interventions. The authors find that task structure and access to internal states can matter more than reasoning mode. This supports precise labels for which output surface a monitor actually sees.','Math and question answering; explicit, weakly supervised and strongly supervised latent reasoning.'],
'2608.29070': ['Implicit influence','Studies whether benign and malign hidden directives appear differently in returned reasoning. The authors report disclosure asymmetries and activation-steering results. Disclosure frequency alone is not a complete measure of whether a directive causally affected an answer.','Eight reasoning models; behavioral controls and a separately described steering evaluation.'],
'2609.04343': ['Implicit influence','Proposes removing input concepts that an explanation does not credit, then querying the model again. The authors report improved explanation completeness in their tested datasets. This is a relevant attempted mitigation, with transfer to our tasks and observation surface unestablished.','Two datasets and multiple model families; test-time intervention without changing weights.'],
'2607.23458': ['Measurement','Audits behavioral faithfulness metrics against annotated traces. Performance differs substantially between correct and incorrect answers, and some familiar signals fail in the regime containing most annotated unfaithfulness. A convenient metric needs validation for the population being studied.','FaithCoT-Bench audit; model- and source-dependent transfer results.'],
'2609.02754': ['Accessible reasoning','Examines misleading context in medical question answering and compares disclosure in reasoning traces with disclosure in final responses. Monitoring results vary with access and cue type. This is methodological context, not medical guidance or a demonstration task.','Three reasoning models on a clinician-reviewed benchmark; output accessibility differs by model.'],
'2607.06648': ['Reward compatibility','Tracks faithfulness-related behavior and activation interventions through latent-reasoning training. Strong final accuracy can coexist with declining counterfactual responsiveness. The results motivate checking a training trajectory rather than assuming a final checkpoint captures all changes.','Latent reasoning on ProsQA and GSM settings; intervention dependence is a stated limitation.'],
'2606.28166': ['Reward compatibility','Co-generates reasoning between a trained senior model and a fixed junior during reinforcement learning. The authors report improved handoff robustness and junior-model legibility while maintaining solo capability. Communication compatibility is relevant but does not establish safety monitorability.','Qwen3-4B-Instruct competition-math training; junior-model compatibility.'],
'2607.08066': ['Oversight','Tests whether an agent\'s written reasoning can persuade a monitor to approve a policy-violating proposal. The authors evaluate a fact-checking intervention, with model diversity affecting its performance. This studies adversarial persuasion, a different mechanism from our benign contextual cues.','Forty tasks; reported examples include Claude 3.7 Sonnet and GPT-4.1, so publication recency is not model recency.'],
'2609.07162': ['Measurement','Formalizes limits on properties that require comparing executions, and separates missing information from failures to apply a comparison procedure. The paper also reports a benchmark-construction error found despite favorable judge reviews. Its synthetic settings require careful transfer claims.','Synthetic leak families and replay comparisons; theoretical and empirical claims not independently replicated here.'],
'2609.05797': ['Oversight','Separates monitor recall on harmful prompts that a target model will comply with from recall on prompts it will refuse. The reported gap shows why a monitor\'s aggregate classification score may differ from the protection it provides in a coupled system.','Six monitor configurations and three model families; harmfulness labels and compliance are different targets.'],
'2608.24232': ['Oversight','Introduces evidence annotations across prompts, reasoning traces and final responses. The authors find guardrail models struggle to locate supporting evidence in reasoning. The benchmark addresses unsafe-content judgment, which is distinct from detecting an influence on a decision.','Eighteen guardrail models and traces from four reasoning models.'],
'2609.00264': ['Measurement','Tests whether reference-answer access improves reasoning verification or mainly reveals a mismatch with the conclusion. Monitors can benefit overall while missing genuine errors in traces whose final answer is correct. Correctness and sound reasoning should remain separate measures.','237 solutions to 79 physics questions; eight monitors and independently labeled errors.'],
'2608.03745': ['Accessible reasoning','Intervenes directly on reasoning text to study the tension between following a trace and rejecting unsafe reasoning. The authors describe a task-specific faithfulness-safety tradeoff and a steering intervention. Greater trace dependence is not automatically greater safety.','HazMart shopkeeper setting with reasoning replacement and open-model analysis.'],
'2603.30036': ['Reward compatibility','Models output rewards and reasoning rewards as aligned, orthogonal or in conflict, then tests predicted monitorability changes during training. Appendix I.7 already studies capped continuation. That comparison is prior work, and a tiny inference-time pilot cannot reproduce long training drift.','Older foundation, submitted March 2026; training experiments require resources beyond the core API demonstration.'],
'2603.28590': ['Measurement','Provides a multi-task monitorability benchmark with controlled decision-critical factors and prompting stress tests. The authors find that task structure, subject model and monitor all matter. Its August revision is recent, but its original submission is March.','Older foundation, 1,514 instances across 19 tasks; updated August 2026.']
};
const papers=[];
for(const [id,[area,abstract,modelScope]] of Object.entries(notes)){
 const meta=JSON.parse(await fs.readFile(`.cache/papers/${id}.json`,'utf8'));
 const version=meta.version?.match(/this version, (v\d+)/)?.[1]??'v1';
 const published=meta.published.replaceAll('/','-');
 const p={id,title:meta.title,authors:meta.authors.map(a=>a.replace('Shah, and Rohin','Shah, Rohin')),published,updated:meta.onlineDate.replaceAll('/','-'),url:`https://arxiv.org/abs/${id}${version}`,version,sourceType:'arXiv preprint',abstract,topics:[area,'AI safety'],verificationStatus:'Primary metadata and abstract checked; findings not independently replicated',featured:published>='2026-06-01',modelScope,checkedAt:meta.checkedAt};papers.push(p);
}
const searchFiles=(await fs.readdir('artifacts/search')).filter(x=>x.endsWith('.json') && x !== 'summary.json');
const searches=await Promise.all(searchFiles.map(async f=>JSON.parse(await fs.readFile('artifacts/search/'+f,'utf8'))));
const allQueries=searches.map(s=>s.request?.query).filter(Boolean);
const search={date:'2026-09-13',queries:allQueries,coverage:'Nine bounded Exa searches across academic papers, lab and researcher sites, public technical discussions and repositories, followed by primary arXiv metadata and abstract checks. Source coverage is selective and English-led.',inaccessible:['Private or unpublished work','Paywalled full text not separately obtained','Comprehensive social-platform and LinkedIn coverage','Search-index omissions and differently worded work']};
const questions=[
{id:'q-implicit-influence',title:'When a cue changes the answer, does the explanation reveal it?',area:'Implicit influence',status:'Partially addressed',origin:'agent-proposed',summary:'Compare the same decision with a neutral context and a contextual cue. Measure changes in choices separately from what a monitor can detect in the returned explanation.',whyItMatters:'Oversight can fail silently if a model changes its behavior while its visible explanation gives a monitor no useful evidence of the influence. A controlled comparison can expose that gap without pretending to read hidden computation.',source:{paperId:'2608.04735',url:'https://arxiv.org/html/2608.04735v1#S3.SS1',version:'v1',section:'Section 3.1, binary preference elicitation; Section 5, limitations',passage:'Nudges span themes including ethical concerns, social proof, sunk cost, and demographic cues.'},closestWork:[{paperId:'2608.04735',finding:'Directly compares implicit and explicit influence with baseline checks and monitors in four task families.',mismatch:'Our affordable API adaptation uses a small decision family and only the output surfaces its endpoint returns. It is not a reproduction of the full benchmark.'},{paperId:'2608.29464',finding:'Studies cue channel and explicitness, plus source-attribution and monitoring-awareness prompts.',mismatch:'Its prefilled-tool and open-weight settings do not establish behavior for our exact endpoint and task distribution.'},{paperId:'2609.04343',finding:'Removes uncredited input concepts and re-queries to target explanation incompleteness.',mismatch:'The mitigation changes the input and is not yet evaluated in our locked experiment.'}],uncertainty:'The broad phenomenon has prior evidence. The effect size and monitor behavior in our exact setting remain empirical questions. A failed or null pilot would not settle the broader problem.',search,executable:true,estimatedCostUsd:1,estimatedMinutes:12,access:'API only; owner authorization required',position:{x:63,y:43},evidenceIds:[]},
{id:'q-cue-channel',title:'Does evidence arriving through a tool become harder to notice?',area:'Implicit influence',status:'Partially addressed',origin:'agent-proposed',summary:'Hold a preference cue fixed while changing whether it arrives as a user statement or a tool result.',whyItMatters:'Agents consume tool output as part of ordinary work. Monitoring tests based only on direct user instructions may miss how those channels change cue attribution.',source:{paperId:'2608.29464',url:'https://arxiv.org/abs/2608.29464v2',version:'v2',section:'Abstract, FACE-Eval design',passage:'Every model has lower verbalized commitment for tool-return than user-message cues and for implicit than explicit cues.'},closestWork:[{paperId:'2608.29464',finding:'Reports channel and explicitness effects across 15 open-weight models, with mixed attribution-prompt mitigation.',mismatch:'Transfer to multi-step tools, current proprietary endpoints and other task families is not established by its single-call design.'},{paperId:'2608.04735',finding:'Separates implicit from explicit delivery in matched task formats.',mismatch:'Delivery regime and tool channel are different variables; matching one does not control the other.'}],uncertainty:'An extension must control message role, content, context length and output accessibility. This question is proposal-only and has no Afterlight result.',search,executable:false,access:'API only; protocol not yet validated',position:{x:75,y:28},evidenceIds:[]},
{id:'q-length-pressure',title:'What evidence disappears when reasoning becomes shorter?',area:'Reward compatibility',status:'Partially addressed',origin:'agent-proposed',summary:'Separate a shorter visible trace from a training process that changes which reasoning gets expressed.',whyItMatters:'Reducing inference cost is useful, but preserving task accuracy alone may hide a loss of evidence available to an overseer.',source:{paperId:'2607.09786',url:'https://arxiv.org/abs/2607.09786v3',version:'v3',section:'Abstract, length-matched control',passage:'Shorter chains of thought mention misleading hints less often, but the hints still influence the models\' answers.'},closestWork:[{paperId:'2607.09786',finding:'Compares trained compression against deletion controls matched in length across five distributions.',mismatch:'A maximum-output setting at inference time is not the same intervention as training with length penalties.'},{paperId:'2603.30036',finding:'Relates reasoning and outcome reward compatibility to monitorability changes.',mismatch:'Its training mechanism does not identify a safe universal inference-time length cap.'}],uncertainty:'A useful comparison needs accuracy, influence and false-positive controls. Training replication requires model access and compute. No safe universal cap is claimed.',search,executable:false,access:'Training compute for faithful replication; API variant is a different study',position:{x:84,y:62},evidenceIds:[]},
{id:'q-reward-drift',title:'Can reasoning stay legible as optimization continues?',area:'Reward compatibility',status:'Partially addressed',origin:'agent-proposed',summary:'Investigate when continued optimization changes the evidence available to a fixed monitor.',whyItMatters:'An oversight method validated at one checkpoint may not preserve its behavior after training or reward changes.',source:{paperId:'2603.30036',url:'https://arxiv.org/html/2603.30036v1',version:'v1',section:'Abstract; Appendix I.7 is prior capped-continuation work',passage:'We model LLM post-training as an RL environment where the reward decomposes into two terms'},closestWork:[{paperId:'2603.30036',finding:'Tests a reward-compatibility framework and already compares unrestricted with capped continuation in Appendix I.7.',mismatch:'That comparison is established prior work. A fixed representation convention and transfer to current endpoints would require a new, controlled protocol.'},{paperId:'2606.28166',finding:'Uses a fixed junior model during training to encourage legible, compatible reasoning.',mismatch:'Junior-model communication compatibility is not itself a safety-monitor detection guarantee.'},{paperId:'2607.06648',finding:'Shows that a final checkpoint can conceal changing faithfulness-related behavior along training.',mismatch:'Latent-reasoning interventions and API-visible explanation monitoring use different access and measurements.'}],uncertainty:'Drift can require hundreds of iterations. We have not run this experiment and do not present a tiny inference pilot as a training replication.',search,executable:false,access:'Training compute and checkpoint access',position:{x:68,y:72},evidenceIds:[]},
{id:'q-visible-evidence',title:'How much can a monitor infer from the text it receives?',area:'Accessible reasoning',status:'Partially addressed',origin:'agent-proposed',summary:'Treat visible explanations, returned reasoning tokens and internal activations as different observation surfaces.',whyItMatters:'A monitor can only use the evidence it actually receives. A convincing explanation does not prove that all decision-relevant computation is visible.',source:{paperId:'2608.04928',url:'https://arxiv.org/abs/2608.04928v1',version:'v1',section:'Abstract, monitoring-access comparison',passage:'monitorability depends more on properties of the task'},closestWork:[{paperId:'2608.04928',finding:'Compares reasoning modes with differing task structure and internal access.',mismatch:'Its hint-based tasks do not quantify all forms of real-world hidden influence.'},{paperId:'2607.22925',finding:'Finds consequential behavior with semantically uninformative filler tokens in synthetic tasks.',mismatch:'Invisible computation is a demonstrated possibility, not an explanation for every missed cue.'},{paperId:'2609.02754',finding:'Compares cue disclosure and monitoring from returned traces and responses.',mismatch:'Its medical benchmark and provider access differ from this laboratory\'s benign decision tasks.'}],uncertainty:'Readability, faithfulness, task correctness and monitorability are distinct. No claim of access to private internal reasoning is made.',search,executable:false,access:'Depends on the observation surface; internal probes require weights',position:{x:53,y:61},evidenceIds:[]},
{id:'q-monitor-measurement',title:'Is the monitor detecting influence, or judging a plausible story?',area:'Measurement',status:'Unassessed',origin:'agent-proposed',summary:'Validate explanation judgments against controlled changes, negative controls and the full set of attempted trials.',whyItMatters:'A high aggregate score can conceal failures in the cases that matter. Monitor judgments need an independently defined target and clear denominators.',source:{paperId:'2609.04194',url:'https://arxiv.org/abs/2609.04194v1',version:'v1',section:'Abstract, causal importance and judge estimates',passage:'step importance is only partially recoverable from the text of the reasoning trace'},closestWork:[{paperId:'2609.04194',finding:'Compares judged step importance with continuation-based estimates.',mismatch:'Step importance differs from detecting a contextual cue\'s effect on a decision.'},{paperId:'2609.00264',finding:'Shows that trusted answers can improve conclusion checking while leaving errors in correct-answer traces missed.',mismatch:'Reasoning correctness and influence attribution require separate validation.'},{paperId:'2607.23458',finding:'Finds that behavioral faithfulness metrics vary across correct- and incorrect-answer regimes.',mismatch:'The available abstract review does not establish which metric transfers to this task.'}],uncertainty:'This dossier is an agent-proposed synthesis. A complete closest-work assessment and executable criterion have not yet been frozen.',search,executable:false,access:'Protocol design and reviewed labels required',position:{x:86,y:41},evidenceIds:[]}
];
const edges=questions.flatMap(q=>[{id:`raises-${q.id}`,source:q.source.paperId,target:q.id,type:'raises',explanation:'This paper motivates the agent-proposed question under the stated scope. The paper is not claimed to state this exact question.',evidenceUrl:q.source.url},...q.closestWork.filter(w=>w.paperId!==q.source.paperId).map(w=>({id:`adjacent-${w.paperId}-${q.id}`,source:w.paperId,target:q.id,type:'methodologically adjacent',explanation:w.finding+' Remaining mismatch: '+w.mismatch,evidenceUrl:papers.find(p=>p.id===w.paperId)?.url}))]);
const coverage={searchedAt:new Date().toISOString(),paperCount:papers.length,questionCount:questions.length,recentPaperCount:papers.filter(p=>p.featured).length,foundationCount:papers.filter(p=>!p.featured).length,note:'A selected monitorability neighborhood: 18 papers first submitted June to September 2026, plus 2 older foundations. Six agent-proposed dossiers; five scoped assessments and one unassessed synthesis. This is not a comprehensive map of AI safety.',searchCount:searches.length,searchCostUsd:searches.reduce((s,x)=>s+(x.costDollars?.total??0),0),searchArtifactUrl:'https://github.com/RaphaelKhalid/afterlight/tree/main/artifacts/search'};
const corpus=addPersonaProposal({questions,papers,edges,coverage});
await fs.writeFile('public/data/corpus.json',JSON.stringify(corpus,null,2));
await fs.writeFile('artifacts/sources/corpus.json',JSON.stringify(corpus,null,2));
await fs.writeFile('artifacts/search/summary.json',JSON.stringify({...coverage,queries:allQueries,limitations:search.inaccessible,scope:search.coverage},null,2));
console.log(JSON.stringify(coverage));

